---
title: "Research Interests"
output: html_document
---
<!--- <h3>Research Interests</h3> --->
<ul>
    <li> Statistical machine learning algorithms for precision medicine and computational Biology with a particular emphasis on Computational Pathology</li>
    <li> Deep learning algorithms for large scale medical imaging (e.g. <a href="https://www.pixelscientia.com/article-finding-prognostic-patterns-in-gigapixel-images.html">whole slide images</a>) </li>
    <li>  Computational/statistical approaches for tissue omics e.g. characterization of the tumor microenvironment through H&E, multiplex immunofluorescence, spatial transcriptomics, etc</li>
    <li>  Multi-modal/view data analytic methodology</li>
    <li>  Statistical analysis of structured data (networks, structured sparsity, etc)
</li>
</ul>


<hr><br>
<!---
<h3>Research Interests</h3>
<ul>
    <li> Statistical machine learning </li>
    <li> Precision medicine and compuational pathology</li>
    <li> Deep learning for medical image analysis </li>
    <li> Structured sparsity </li>
    <li> Network analysis </li>
    <li> Multi-view/modal data integration </li>
    <li> Structured sparsity/high dimensional regression </li>
</ul>
<hr><br>
--->

<h3>Conference Presentations and Posters</h3>
<ul>
    <li> Carmichael, I., Song, A.H., Chen, R.J., Williamson, D.F.K., Chen, T.Y., Mahmood, F. Incorporating intratumoral heterogeneity into weakly-supervised deep learning models via variance pooling. Digital Pathology & AI Congress USA. New York, NY. June, 2022.</li><br>
    <li> Olayinka, O., Carmichael, I., Gaeta Gazzola, M., Dimeola, K.A., Zheng, Z., Madden, L.M., Beitel, M., Barry, D.T. Sex Differences among Individuals with Chronic Pain and Opioid Use Disorder Entering Methadone Maintenance Treatment. College on Problems of Drug Dependence. Minneapolis, Minnesota. June, 2022.</li><br>
    <li> Gaeta, M., Carmichael, I., Madden, L., Beitel, M., Eggert, K., Barry, D.T. Patient Characteristics and Retention among Homeless Patients Enrolled in a Low-Barrier-To Treatment-Entry Medication for Opioid Use Disorder Program. College on Problems of Drug Dependence.  Online. June, 2021.</li><br>
    <li> Fusion of image and genetic data with convolutional neural networks and AJIVE, <a href="">Bayesian, Fiducial, and Frequentist (BFF) Conference</a>. Durham, NC. April, 2019. (<a href="/assets/carmichael_bff_2019_compressed.pdf">poster</a>)</li><br>
    <li> Angle-based Joint and Individual Variation Explained with Applications to Image and Genetic Data, <a href="https://www.mn.uio.no/math/english/research/projects/focustat/news-and-events/">FocuStat Combo Kitchen</a>. Oslo, Norway. November, 2018</li><br>
    <li> Anlge Based Joint and Individual Variation Explained, <a href="https://www.bi.vt.edu/nsf-big-data-2018"> NSF Big Data Hubs and Spokes Join PI meeting</a>. Alexandria, VA. June, 2018. (<a href="/assets/ajive_carmichael_nsf_bigdata2018_poster.pdf">poster</a>)</li>
</ul>
<hr><br>

<h3>Talks</h3>
Slides not linked to below are available upon request.
<br>
<ul>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. UC Berkeely, Department of Biostatistics. Berkeley, CA. March, 2022. </li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. The Flatiron Institute, Center for Computational Mathematics. March, 2022. </li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. University of British Columbia, Department of Statistics. Vancouver, Canada. Feb, 2022. </li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. University of Michigan, Department of Biostatistics. Ann Arbor, MI. Jan, 2022. </li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. NYU Grossman School of Medicine, Division of Biostatistics. NYC, NY. November, 2021.</li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. University of North Carolina at Chapel Hill, Department of Statistics and Operations Research. Chapel Hill, NC. September, 2021.</li><br>
    <li> The folded concave Laplacian spectral penalty learns block diagonal sparsity patterns with the strong oracle property. University of Washington, Department of Statistics. Seattle, WA. June, 2021.</li><br>
    <li> Sparsity Structure Estimation for Multi-View Mixture Models. University of Washington, Department of Statistics. Seattle, WA. May, 2020.</li><br>
    <li> Joint and individual analysis of breast cancer histologic images and genomic covariates, Harvard Medical School. Boston, MA. December, 2019. (<a href="/assets/joint_image_genetics.pdf">Slides</a>)</li><br>
    <li> Joint and individual analysis of histopathology images and genetic covariates. Computational Medicine group, UNC Chapel Hill. May, 2019.</li><br>
    <li> Angle-based Joint and Individual Variation Explained with Applications to Image and Genetic Data. University of Illinois Urbana-Champaign, Department of Statistics. Urbana, IL. February, 2019.</li><br>
    <li> Angle-based Joint and Individual Variation Explained with Applications to Image and Genetic Data. University of Wisconsin-Madison, Department of Statistics. Madison, WI. January, 2019.</li><br>
    <li> Angle-based Joint and Individual Variation Explained with Applications to Image and Genetic Data. Harvard University, Department of Biostatistics. Boston, MA. January, 2019.</li><br>
    <li> Joint analysis of H&E stained images and genetic covariates using deep learning and AJIVE. GenStat group, UNC Chapel Hill. September, 2018.</li><br>
    <li>  <a href="http://stat-or.unc.edu/event/stor-colloquium-iain-davis-unc-chapel-hill"> Data Science and the Undergraduate Curriculum</a>. UNC STOR Department Colloquium. Chapel Hill, NC. October, 2017. (<a href="/assets/data_science_stor_colloquium.pdf">Slides</a>)</li><br>
    <li> <a href="https://www.youtube.com/watch?v=AP7_godzwVI"> Open Data, Networks and the Law</a> by Iain Carmichael and Michael Kim. PyData Carolinas, 2016.</li>
</ul>
<hr><br>
<h3>Past Projects</h3>
<ul>
<br>
    <li>
    <b>Probabilistic Programming</b> (summer 2016)<br>
    Summer internship at <a href="https://gamalon.com/">Gamalon Machine Intelligence</a>. Worked on theoretical problems in probabilistic programming and contributed to the development of Chimpy, a probabilistic programming language in Python.
    </li> <br>
    <li>
    <b>Regional Coverage from Space Systems</b> (summer 2012)<br>
     Developed algorithms for satellite regional coverage problems at the NSF sponsored <a href="http://www.ipam.ucla.edu/programs/student-research-programs/research-in-industrial-projects-for-students-rips-2017/">RIPS</a> program. Collaboration with  <a href="http://www.ipam.ucla.edu/">Institute for Pure and Applied Mathematics</a> and the <a href="http://www.aerospace.org/">Aerospace Corporation</a>.
    </li>
</ul>
